-- Canonical seed for the `banking_ops` pipeline stage.
-- Generated by `cargo run --bin dump_rules` (editable-rules-v3 §6).
-- Edit via the Pipeline tab; this file is re-dumped on each change.
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('BPay', '(?i)BPAY PAYMENT', 0, NULL, 0);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('BPay', '(?i)ANZ INTERNET BANKING BPAY', 0, NULL, 1);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Deposit', '(?i)CASH DEPOSIT', 0, NULL, 2);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Fee', '(?i)ACCOUNT SERVICING FEE', 0, NULL, 3);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Fee', '(?i)ACCOUNT FEE$', 0, NULL, 4);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Fee', '(?i)ADMINISTRATION FEE$', 0, NULL, 5);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Fee', '(?i)CONTRIBUTION TAX ADJUSTMENT$', 0, NULL, 6);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Fee', '(?i)CONTRIBUTION TAX$', 0, NULL, 7);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Fee', '(?i)INTERNATIONAL TRANSACTION FEE', 0, NULL, 8);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Fee', '(?i)UNPAID PAYMENT FEE', 0, NULL, 9);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Fee', '(?i)PACKAGE FEE$', 0, NULL, 10);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Direct Credit', '(?i)PAYID PAYMENT RECEIVED', 0, NULL, 11);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Interest', '(?i)INTEREST CHARGE', 0, NULL, 12);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Interest', '(?i)INTEREST ADJUSTMENT', 0, NULL, 13);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Interest', '(?i)INTEREST CORRECTION', 0, NULL, 14);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Internal Transfer', '(?i)INTERNAL TRANSFER', 1, NULL, 15);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Internal Transfer', '(?i)TRANSFER (?:TO|FROM) XX(?P<account>\d{4})', 1, NULL, 16);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Internal Transfer', '(?i)(?:TO|FROM) ACCOUNT XX(?P<account>\d{4})', 1, NULL, 17);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Loan', '(?i)LOAN REPAYMENT', 0, NULL, 18);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Loan', '(?i)REPAYMENT/PAYMENT', 0, NULL, 19);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Transfer', '(?i)FUNDS TRANSFER', 0, NULL, 20);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Transfer', '(?i)ONLINE PAYMENT RECEIVED', 0, NULL, 21);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Transfer', '(?i)TRANSFER TO CBA', 0, NULL, 22);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Transfer', '(?i)TRANSFER TO OTHER BANK', 0, NULL, 23);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Credit Card', '(?i)CREDIT CARD', 0, NULL, 24);
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order) VALUES ('Withdrawal', '(?i)WDL ATM', 0, NULL, 25);
