-- Canonical seed for the `employers` pipeline stage.
-- Generated by `cargo run --bin dump_rules` (editable-rules-v3 §6).
-- Edit via the Pipeline tab; this file is re-dumped on each change.
INSERT INTO rule_employers (canonical, pattern, note) VALUES ('AFES', '(?i)(?:Salary from|From) AFES', NULL);
INSERT INTO rule_employers (canonical, pattern, note) VALUES ('Apple', '(?i)(?:PAY/SALARY FROM|Salary from|TRANSFER FROM|From) APPLE (?:COMPUTERS|PTY LTD|COMPUTER AUSTRALIA)', NULL);
INSERT INTO rule_employers (canonical, pattern, note) VALUES ('Apple', '(?i)Employer Contribution From Apple', NULL);
INSERT INTO rule_employers (canonical, pattern, note) VALUES ('Freelancer', '(?i)(?:Salary.*Freelancer|Employer Contribution From Freelancer)', NULL);
INSERT INTO rule_employers (canonical, pattern, note) VALUES ('Ghost Locomotion', '(?i)(?:Salary.*GHOST LOCOMOTION|Employer Contribution From Ghost Locomotion|Ghost Locomotion.*(?:Receipt|Salary))', NULL);
