-- Canonical seed for the `banking_ops` pipeline stage.
-- Generated by `pocketsmith dump` (editable-rules-v3 §6).
-- Edit via the Pipeline tab; this file is re-dumped on each change.
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('BPay', '(?i)BPAY PAYMENT', 0, NULL, 0, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('BPay', '(?i)ANZ INTERNET BANKING BPAY', 0, NULL, 1, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Deposit', '(?i)CASH DEPOSIT', 0, NULL, 2, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Fee', '(?i)ACCOUNT SERVICING FEE', 0, NULL, 3, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Fee', '(?i)ACCOUNT FEE$', 0, NULL, 4, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Fee', '(?i)ADMINISTRATION FEE$', 0, NULL, 5, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Fee', '(?i)CONTRIBUTION TAX ADJUSTMENT$', 0, NULL, 6, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Fee', '(?i)CONTRIBUTION TAX$', 0, NULL, 7, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Fee', '(?i)INTERNATIONAL TRANSACTION FEE', 0, NULL, 8, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Fee', '(?i)UNPAID PAYMENT FEE', 0, NULL, 9, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Fee', '(?i)PACKAGE FEE$', 0, NULL, 10, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Direct Credit', '(?i)PAYID PAYMENT RECEIVED', 0, NULL, 11, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Interest', '(?i)INTEREST CHARGE', 0, NULL, 12, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Interest', '(?i)INTEREST ADJUSTMENT', 0, NULL, 13, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Interest', '(?i)INTEREST CORRECTION', 0, NULL, 14, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Internal Transfer', '(?i)INTERNAL TRANSFER', 1, NULL, 15, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Internal Transfer', '(?i)TRANSFER (?:TO|FROM) XX(?P<account>\d{4})', 1, NULL, 16, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Internal Transfer', '(?i)(?:TO|FROM) ACCOUNT XX(?P<account>\d{4})', 1, NULL, 17, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Loan', '(?i)LOAN REPAYMENT', 0, NULL, 18, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Loan', '(?i)REPAYMENT/PAYMENT', 0, NULL, 19, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Transfer', '(?i)FUNDS TRANSFER', 0, NULL, 20, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Transfer', '(?i)ONLINE PAYMENT RECEIVED', 0, NULL, 21, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Transfer', '(?i)TRANSFER TO CBA', 0, NULL, 22, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Transfer', '(?i)TRANSFER TO OTHER BANK', 0, NULL, 23, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Credit Card', '(?i)CREDIT CARD', 0, NULL, 24, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_banking_ops (operation, pattern, has_account, note, sort_order, created_at, updated_at) VALUES ('Withdrawal', '(?i)WDL ATM', 0, NULL, 25, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
