-- Canonical seed for the `employers` pipeline stage.
-- Generated by `cargo run --bin dump` (editable-rules-v3 §6).
-- Edit via the Pipeline tab; this file is re-dumped on each change.
INSERT INTO rule_employers (canonical, pattern, note, created_at, updated_at) VALUES ('AFES', '(?i)(?:Salary from|From) AFES', NULL, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_employers (canonical, pattern, note, created_at, updated_at) VALUES ('Apple', '(?i)(?:PAY/SALARY FROM|Salary from|TRANSFER FROM|From) APPLE (?:COMPUTERS|PTY LTD|COMPUTER AUSTRALIA)', NULL, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_employers (canonical, pattern, note, created_at, updated_at) VALUES ('Apple', '(?i)Employer Contribution From Apple', NULL, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_employers (canonical, pattern, note, created_at, updated_at) VALUES ('Freelancer', '(?i)(?:Salary.*Freelancer|Employer Contribution From Freelancer)', NULL, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
INSERT INTO rule_employers (canonical, pattern, note, created_at, updated_at) VALUES ('Ghost Locomotion', '(?i)(?:Salary.*GHOST LOCOMOTION|Employer Contribution From Ghost Locomotion|Ghost Locomotion.*(?:Receipt|Salary))', NULL, '2026-04-03T12:40:21Z', '2026-04-03T12:40:21Z');
